spring:
  application:
    name: app
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.boot: INFO
    org.springframework.context: DEBUG
    org.springframework.aop: DEBUG
    org.example: DEBUG

encryption:
  secret: mySuperSecretKey1234567890123456

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
